services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      mysql-db:
        condition: service_healthy

  eureka-server:
    build: ./eureka-server-electro
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_started

  api-gateway:
    build: ./api-gateway-electro
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_started

  producto-service:
    build: ./producto-service-electro
    container_name: producto-service
    ports:
      - "8081:8080"   # host:container
    environment:
      SERVER_PORT: "8080"
      SPRING_APPLICATION_NAME: "producto-service"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/producto_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "bruno"
      SPRING_DATASOURCE_PASSWORD: "1234"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_started

  carrito-service:
    build: ./carrito-service-electro
    container_name: carrito-service
    ports:
      - "8082:8080"
    environment:
      SERVER_PORT: "8080"
      SPRING_APPLICATION_NAME: "carrito-service"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/carrito_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "bruno"
      SPRING_DATASOURCE_PASSWORD: "1234"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_started

  venta-service:
    build: ./venta-service-electro
    container_name: venta-service
    ports:
      - "8083:8080"
    environment:
      SERVER_PORT: "8080"
      SPRING_APPLICATION_NAME: "venta-service"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/venta_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "bruno"
      SPRING_DATASOURCE_PASSWORD: "1234"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_started

volumes:
  mysql_data:
