CREATE DATABASE IF NOT EXISTS producto_db;
CREATE DATABASE IF NOT EXISTS carrito_db;
CREATE DATABASE IF NOT EXISTS venta_db;


CREATE USER 'bruno'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON *.* TO 'bruno'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;