server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: carrito-service-electro   # ⚠️ ojo, que coincida con tu config-data

  datasource:
    url: jdbc:mysql://mysql-db:3306/carrito_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: bruno
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

# --- Resilience4j (Circuit Breaker + Retry) ---
resilience4j:
  circuitbreaker:
    instances:
      productosCB:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      productosRetry:
        max-attempts: 3
        wait-duration: 2s

# --- Swagger / OpenAPI ---
springdoc:
  swagger-ui:
    path: /docs

# --- Actuator ---
management:
  endpoints:
    web:
      exposure:
        include: "*"
